---
- name: install apache2 on kub server
  hosts: kub
  become: True  

  tasks:
  - name: Ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
  - name: start apache2 service
    service:
      name: apache2
      state: started
  - name: create apache index.html file
    copy:
      content: "welcome to my web server"
      dest:  /var/www/html/index.html   
...
